Cities = [
"New York, New York",
"Los Angeles, California",
"Chicago, Illinois",
"Houston, Texas",
"Philadelphia, Pennsylvania",
"Phoenix, Arizona	",
"San Antonio, Texas",
"San Diego, California",
"Dallas, Texas",
"San Jose, California",
"Austin, Texas",
"Jacksonville, Florida",
"San Francisco, California",
"Indianapolis, Indiana",
"Columbus, Ohio",
"Fort Worth, Texas",
"Charlotte, North Carolina",
"Detroit, Michigan",
"El Paso, Texas",
"Seattle, Washington",
"Denver, Colorado",
"Washington, District of Columbia",
"Memphis, Tennessee",
"Boston, Massachusetts",
"Nashville, Tennessee",
"Baltimore, Maryland",
"Oklahoma, City	Oklahoma",
"Portland, Oregon",
"Las Vegas, Nevada",
"Louisville, Kentucky",
"Milwaukee, Wisconsin",
"Albuquerque, New Mexico",
"Tucson, Arizona",
"Fresno, California",
"Sacramento, California",
"Long Beach, California",
"Kansas City, Missouri",
"Mesa, Arizona",
"Atlanta, Georgia",
"Virginia Beach, Virginia",
"Omaha, Nebraska",
"Colorado Springs, Colorado",
"Raleigh, North Carolina",
"Miami, Florida",
"Oakland, California",
"Minneapolis, Minnesota",
"Tulsa, Oklahoma",
"Cleveland, Ohio",
"Wichita, Kansas",
"New Orleans, Louisiana",
"Arlington, Texas",
"Bakersfield, California",
"Tampa, Florida",
"Aurora, Colorado",
"Honolulu, Hawai'i",
"Anaheim, California",
"Santa Ana, California",
"Corpus Christi, Texas",
"Riverside, California",
"St. Louis, Missouri",
"Lexington, Kentucky",
"Pittsburgh, Pennsylvania",
"Stockton, California",
"Anchorage, Alaska",
"Cincinnati, Ohio",
"Saint Paul, Minnesota",
"Greensboro, North Carolina",
"Toledo, Ohio",
"Newark, New Jersey",
"Plano, Texas",
"Henderson, Nevada",
"Lincoln, Nebraska",
"Orlando, Florida",
"Jersey City, New Jersey",
"Chula Vista, California",
"Buffalo, New York",
"Fort Wayne, Indiana",
"Chandler, Arizona",
"St. Petersburg, Florida",
"Laredo, Texas",
"Durham, North Carolina",
"Irvine, California",
"Madison, Wisconsin",
"Norfolk, Virginia",
"Lubbock, Texas",
"Gilbert, Arizona",
"Winston–Salem, North Carolina",
"Glendale, Arizona",
"Reno, Nevada",
"Hialeah, Florida",
"Garland, Texas",
"Chesapeake, Virginia",
"Irving, Texas",
"Las Vegas, Nevada",
"Scottsdale, Arizona",
"Baton Rouge, Louisiana",
"Fremont, California",
"Richmond, Virginia",
"Boise, Idaho",
"San Bernardino, California"
]
