Universities = [
  "Princeton University",
  "Harvard University",
  "Yale University",
  "Columbia University",
  "Stanford University",
  "University of Chicago",
  "Massachusetts Institute of Technology",
  "Duke University",
  "University of Pennsylvania",
  "California Institute of Technology",
  "University College London",
  "University of California, Berkeley",
  "University of Oxford",
  "University of California, Los Angeles",
  "Imperial College London",
  "University of California, San Diego",
  "ETH Zurich",
  "Queen Mary University of London",
  "Cornell University",
  "University of Michigan",
  "University of Texas at Austin",
  "Brown University",
  "University of Notre Dame",
  "Vanderbilt University",
  "Georgetown University",
  "Carnegie Mellon University",
  "University of North Carolina",
  "University of Illinois - Urbana-Champaign",
  "University of Florida",
  "University of Washington",
  "University of Pittsburgh"
]
